# Frontend Dockerfile
FROM node:20-alpine as build
WORKDIR /app
COPY frontend /app/frontend
WORKDIR /app/frontend
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=build /app/frontend/build /usr/share/nginx/html
COPY deploy/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
